"""iptu payments

Revision ID: 38309a00f58b
Revises: dbde09cccf91
Create Date: 2026-06-08 19:38:41.456590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38309a00f58b'
down_revision: Union[str, None] = 'dbde09cccf91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iptu_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('bank_txn_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bank_txn_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'year', name='uq_iptu_property_year')
    )
    op.create_index(op.f('ix_iptu_payments_property_id'), 'iptu_payments', ['property_id'], unique=False)
    op.create_index(op.f('ix_iptu_payments_year'), 'iptu_payments', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_iptu_payments_year'), table_name='iptu_payments')
    op.drop_index(op.f('ix_iptu_payments_property_id'), table_name='iptu_payments')
    op.drop_table('iptu_payments')
    # ### end Alembic commands ###
