"""bank transactions

Revision ID: dbde09cccf91
Revises: 1631b5106324
Create Date: 2026-06-07 16:09:56.305528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbde09cccf91'
down_revision: Union[str, None] = '1631b5106324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('fitid', sa.String(length=120), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.Enum('credit', 'debit', name='txnkind'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counterparty_name', sa.String(length=255), nullable=True),
    sa.Column('counterparty_doc', sa.String(length=40), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reconciled', 'ignored', name='reconstatus'), nullable=False),
    sa.Column('rent_charge_id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rent_charge_id'], ['rent_charges.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'fitid', name='uq_bank_acct_fitid')
    )
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_fitid'), 'bank_transactions', ['fitid'], unique=False)
    op.create_index(op.f('ix_bank_transactions_kind'), 'bank_transactions', ['kind'], unique=False)
    op.create_index(op.f('ix_bank_transactions_posted_date'), 'bank_transactions', ['posted_date'], unique=False)
    op.create_index(op.f('ix_bank_transactions_status'), 'bank_transactions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_transactions_status'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_posted_date'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_kind'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_fitid'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    # ### end Alembic commands ###
